/* Config Editor for the plugin's main config.yml.
 *
 * The whole file is held as one parsed JS object (state). Friendly forms edit
 * the commonly-tuned sections by mutating that object in place; any sections
 * the forms don't model (stations, tools, routing, quality.consumption, ...)
 * survive an upload untouched. Output is produced by YAMLLite.dump.
 */
"use strict";

const STORE_KEY = "config-editor-v2";
const OLD_STORE_KEY = "config-editor-v1";
const $ = (id) => document.getElementById(id);

function num(v, fallback) { const n = parseFloat(v); return isNaN(n) ? fallback : n; }
function clamp(v, lo, hi) { return Math.min(hi, Math.max(lo, v)); }

function defaultConfig() {
  return YAMLLite.parse(C4_DEFAULT_CONFIG_YAML);
}

const QUALITY_TIERS = ["poor", "decent", "good", "perfect"];

let state = load();

function load() {
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (raw) return JSON.parse(raw);
    const old = localStorage.getItem(OLD_STORE_KEY);
    if (old) {
      const migrated = mergeDefaults(defaultConfig(), JSON.parse(old));
      localStorage.setItem(STORE_KEY, JSON.stringify(migrated));
      return migrated;
    }
  } catch (e) { /* fall through */ }
  return defaultConfig();
}

function mergeDefaults(defaults, saved) {
  if (!defaults || typeof defaults !== "object" || Array.isArray(defaults)) {
    return saved === undefined ? defaults : saved;
  }
  if (!saved || typeof saved !== "object" || Array.isArray(saved)) return defaults;
  const merged = { ...defaults };
  for (const key of Object.keys(saved)) {
    merged[key] = key in defaults ? mergeDefaults(defaults[key], saved[key]) : saved[key];
  }
  return merged;
}

function save() {
  try { localStorage.setItem(STORE_KEY, JSON.stringify(state)); } catch (e) { /* full/blocked */ }
}

// Ensure a nested path exists, returning the leaf object.
function sect(...path) {
  let o = state;
  for (const k of path) { if (!o[k] || typeof o[k] !== "object") o[k] = {}; o = o[k]; }
  return o;
}

// ── render ───────────────────────────────────────────────────────────────────

function changed() { renderYAML(); save(); }

const CONFIG_SECTION_LABELS = {
  debug: "General",
  tools: "Devices",
  quality: "Quality",
  insanity: "Insanity",
  mcmmo: "mcMMO",
  visuals: "Visuals",
  crop_highlight: "Crop highlight",
  vanilla_foods: "Vanilla food spoilage",
  consumable_groups: "Consumable groups",
  biome_groups: "Biome groups",
  grass_seeds: "Grass seeds",
  vanilla_crops: "Vanilla crops",
  reports: "Bug reports and feedback",
};

function formatConfigYAML(config) {
  const out = [
    "# Generated by tools/config-editor",
    "# Drop into plugins/C4/config.yml",
  ];
  for (const line of YAMLLite.dump(config).trimEnd().split("\n")) {
    const match = /^([A-Za-z0-9_-]+):(?:\s|$)/.exec(line);
    const label = match ? CONFIG_SECTION_LABELS[match[1]] : null;
    if (label) {
      out.push("");
      out.push(`# ____________________ ${label} ____________________`);
    }
    out.push(line);
  }
  return out.join("\n") + "\n";
}

function renderYAML() {
  $("yaml-out").textContent = formatConfigYAML(state);
}

function setVal(id, v) { const e = $(id); if (e) e.value = v == null ? "" : v; }
function setChk(id, v) { const e = $(id); if (e) e.checked = !!v; }

function bindForms() {
  const q = state.quality || sect("quality");
  const ins = sect("insanity");
  const vis = sect("visuals");
  const ch = sect("crop_highlight");
  const vf = sect("vanilla_foods");
  const vc = sect("vanilla_crops");

  const mc = sect("mcmmo");
  setChk("cfg-debug", state.debug);
  setChk("cfg-glint", vis.glint);
  setChk("cfg-particles", vis.particles);
  setChk("mc-enabled", mc.enabled !== false);
  setVal("mc-xp", mc.default_herbalism_xp);
  setVal("mc-chance", mc.herbalism_double_drop_chance);

  setVal("ch-block", ch.block); setVal("ch-thickness", ch.thickness);
  setChk("ch-glow", ch.glow); setVal("ch-color", ch.glow_color);

  setVal("ins-decay", ins.decay_per_check); setVal("ins-dose", ins.dose_factor);
  setVal("ins-craving", ins.craving_gain); setVal("ins-withdrawal", ins.withdrawal_gain);
  setVal("ins-damage", ins.damage_gain);

  const ruined = sect("quality", "ruined_item");
  setVal("ruined-mat", ruined.material); setVal("ruined-name", ruined.name);
  setVal("ruined-lore", ruined.lore);

  setVal("vf-default", vf.default_lifetime_minutes);
  setVal("vc-default", vc.default_outside_rate);

  buildTierRows("quality-thresholds", "Thresholds", sect("quality", "thresholds"), 0, 1, 0.01);
  buildTierRows("quality-multipliers", "Multipliers", sect("quality", "multipliers"), 0, 5, 0.05);
  buildStations();
  buildVanillaFoods();
  buildGroups("biome-groups", sect("biome_groups"));
  buildGroups("consumable-groups", sect("consumable_groups"));
  buildVanillaCrops();
  paintChips();
}

function buildTierRows(rootId, title, obj, min, max, step) {
  const root = $(rootId);
  root.innerHTML = `<div class="hitbox-row"><span class="muted">${title}</span></div>`;
  const row = document.createElement("div");
  row.className = "row";
  QUALITY_TIERS.forEach(tier => {
    const lab = document.createElement("label");
    lab.innerHTML = `${tier} <input type="number" min="${min}" max="${max}" step="${step}" value="${obj[tier] ?? ""}">`;
    lab.querySelector("input").addEventListener("input", (e) => {
      obj[tier] = num(e.target.value, 0); changed();
    });
    row.appendChild(lab);
  });
  root.appendChild(row);
}

function buildVanillaFoods() {
  const items = sect("vanilla_foods", "items");
  const root = $("vf-items");
  root.innerHTML = "";
  for (const key of Object.keys(items)) {
    root.appendChild(kvRow(key, items[key], "MATERIAL", "minutes", true,
      (nk, nv) => { delete items[key]; if (nk) items[nk] = num(nv, 0); changed(); },
      () => { delete items[key]; buildVanillaFoods(); changed(); }));
  }
}

function buildGroups(rootId, obj) {
  const root = $(rootId);
  root.innerHTML = "";
  for (const name of Object.keys(obj)) {
    const members = Array.isArray(obj[name]) ? obj[name] : [];
    root.appendChild(kvRow(name, members.join(", "), "group name", "members (comma separated)", false,
      (nk, nv) => {
        delete obj[name];
        if (nk) obj[nk] = nv.split(",").map(s => s.trim()).filter(Boolean);
        changed();
      },
      () => { delete obj[name]; buildGroups(rootId, obj); changed(); }));
  }
}

function buildVanillaCrops() {
  const crops = sect("vanilla_crops", "crops");
  const root = $("vanilla-crops");
  root.innerHTML = "";
  for (const name of Object.keys(crops)) {
    const c = crops[name] && typeof crops[name] === "object" ? crops[name] : {};
    const card = document.createElement("div");
    card.className = "card";
    card.innerHTML = `
      <div class="card-head">
        <input type="text" data-f="id" value="${esc(name)}" spellcheck="false" style="flex:1" placeholder="WHEAT">
        <button class="danger" data-del>✕</button>
      </div>
      <div class="form-grid">
        <label>biomes (keys or group names, comma separated)
          <input type="text" data-f="biomes" value="${esc((c.biomes || []).join(", "))}" spellcheck="false"></label>
        <label>outside rate (0-1)
          <input type="number" data-f="rate" min="0" max="1" step="0.05" value="${c.outside_rate ?? ""}"></label>
      </div>`;
    card.addEventListener("input", (e) => {
      const f = e.target.dataset.f;
      if (f === "id") {
        const nk = e.target.value.trim();
        if (nk && nk !== name) { crops[nk] = crops[name]; delete crops[name]; changed(); }
        return;
      }
      if (f === "biomes") c.biomes = e.target.value.split(",").map(s => s.trim()).filter(Boolean);
      if (f === "rate") c.outside_rate = num(e.target.value, 0.5);
      crops[name] = c;
      changed();
    });
    card.querySelector("[data-del]").onclick = () => { delete crops[name]; buildVanillaCrops(); changed(); };
    root.appendChild(card);
  }
}

// ── stations ───────────────────────────────────────────────────────────────
// Each station: id, display_name, texture, processes[], oven_top, block, and an
// optional crafting recipe (shapeless list OR shaped pattern + key->material).
// The whole `stations:` map round-trips through YAMLLite untouched except for
// what these forms edit.

const STATION_PROCESSES = [
  "pound", "stir", "fry", "temperature", "distill", "ferment",
  "cut", "sieve", "sequence", "smelt",
];

/** Normalise a parsed recipe section into {mode, shapeless[], pattern[], keys{}}. */
function recipeModel(rec) {
  const m = { mode: "none", shapeless: [], pattern: ["", "", ""], keys: {} };
  if (!rec || typeof rec !== "object") return m;
  if (rec.shaped && typeof rec.shaped === "object") {
    m.mode = "shaped";
    const p = Array.isArray(rec.shaped.pattern) ? rec.shaped.pattern.map(String) : [];
    m.pattern = [p[0] || "", p[1] || "", p[2] || ""];
    m.keys = (rec.shaped.keys && typeof rec.shaped.keys === "object") ? { ...rec.shaped.keys } : {};
  } else if (Array.isArray(rec.shapeless)) {
    m.mode = "shapeless";
    m.shapeless = rec.shapeless.map(String);
  }
  return m;
}

/** Write a recipe model back onto a station object (or delete `recipe` when none). */
function applyRecipe(station, m) {
  if (m.mode === "shapeless") {
    const list = m.shapeless.map(s => s.trim()).filter(Boolean);
    if (list.length) { station.recipe = { shapeless: list }; return; }
  } else if (m.mode === "shaped") {
    const pattern = m.pattern.filter(r => r.length).map(r => r);
    const keys = {};
    for (const k of Object.keys(m.keys)) {
      const mat = String(m.keys[k] || "").trim();
      if (k && mat) keys[k] = mat;
    }
    if (pattern.length && Object.keys(keys).length) {
      station.recipe = { shaped: { pattern, keys } };
      return;
    }
  }
  delete station.recipe;
}

function buildStations() {
  const stations = sect("stations");
  const root = $("stations");
  root.innerHTML = "";
  for (const id of Object.keys(stations)) {
    const s = (stations[id] && typeof stations[id] === "object") ? stations[id] : (stations[id] = {});
    root.appendChild(stationCard(stations, id, s));
  }
}

function stationCard(stations, id, s) {
  const card = document.createElement("div");
  card.className = "card";
  const procs = Array.isArray(s.processes) ? s.processes.map(String) : [];
  const rm = recipeModel(s.recipe);

  card.innerHTML = `
    <div class="card-head">
      <input type="text" data-f="id" value="${esc(id)}" spellcheck="false" style="flex:1" placeholder="station_id">
      <button class="danger" data-del>✕</button>
    </div>
    <div class="form-grid">
      <label>Display name <input type="text" data-f="display_name" value="${esc(s.display_name || "")}"></label>
      <label>Texture (base64 or skin URL) <input type="text" data-f="texture" value="${esc(s.texture || "")}" spellcheck="false"></label>
      <div class="with-chip">
        <label>Block (plate stations; blank = head)
          <input type="text" data-f="block" data-keys="blocks" value="${esc(s.block || "")}" spellcheck="false" placeholder="HEAVY_WEIGHTED_PRESSURE_PLATE"></label>
        <canvas class="tex-chip" data-chip width="16" height="16"></canvas>
      </div>
      <label class="check"><input type="checkbox" data-f="oven_top" ${s.oven_top ? "checked" : ""}> Oven-top (install on a furnace/campfire)</label>
    </div>
    <div class="subsection">
      <strong>Processes</strong>
      <div class="row" data-procs>${STATION_PROCESSES.map(p =>
        `<label class="check"><input type="checkbox" data-proc="${p}" ${procs.includes(p) ? "checked" : ""}> ${p}</label>`).join("")}</div>
    </div>
    <div class="subsection" data-recipe>
      <strong>Crafting recipe</strong>
      <label>Type
        <select data-rmode>
          <option value="none" ${rm.mode === "none" ? "selected" : ""}>none</option>
          <option value="shapeless" ${rm.mode === "shapeless" ? "selected" : ""}>shapeless</option>
          <option value="shaped" ${rm.mode === "shaped" ? "selected" : ""}>shaped</option>
        </select></label>
      <div data-recipe-body></div>
    </div>`;

  // identity / scalar fields
  card.addEventListener("input", (e) => {
    const f = e.target.dataset.f;
    if (!f) return;
    if (f === "id") {
      const nk = e.target.value.trim();
      if (nk && nk !== id && stations[nk] === undefined) {
        stations[nk] = stations[id]; delete stations[id]; id = nk; changed();
      }
      return;
    }
    if (f === "oven_top") s.oven_top = e.target.checked;
    else if (f === "block") { const v = e.target.value.trim(); if (v) s.block = v; else delete s.block; paintStationChip(card, s); }
    else s[f] = e.target.value;
    changed();
  });

  // processes
  card.querySelector("[data-procs]").addEventListener("change", (e) => {
    const p = e.target.dataset.proc;
    if (!p) return;
    const set = new Set(Array.isArray(s.processes) ? s.processes : []);
    if (e.target.checked) set.add(p); else set.delete(p);
    s.processes = [...set];
    changed();
  });

  // recipe mode + body
  const body = card.querySelector("[data-recipe-body]");
  const drawRecipe = () => renderRecipeBody(body, rm, () => { applyRecipe(s, rm); changed(); });
  card.querySelector("[data-rmode]").addEventListener("change", (e) => {
    rm.mode = e.target.value; applyRecipe(s, rm); drawRecipe(); changed();
  });
  drawRecipe();

  card.querySelector("[data-del]").onclick = () => { delete stations[id]; buildStations(); changed(); };
  MCAssets.onReady(() => paintStationChip(card, s));
  paintStationChip(card, s);
  return card;
}

function paintStationChip(card, s) {
  const canvas = card.querySelector("[data-chip]");
  chip(canvas, matTex((s.block || "").trim()));
}

/** Render the shapeless/shaped recipe editor into `body` for model `rm`. */
function renderRecipeBody(body, rm, onChange) {
  body.innerHTML = "";
  if (rm.mode === "shapeless") {
    const hint = document.createElement("p");
    hint.className = "hint";
    hint.textContent = "Materials consumed in any arrangement (comma separated).";
    body.appendChild(hint);
    const input = document.createElement("input");
    input.type = "text"; input.spellcheck = false;
    input.dataset.keys = "items";
    input.dataset.multi = "";
    input.placeholder = "STONE, BOWL, STICK";
    input.value = rm.shapeless.join(", ");
    input.addEventListener("input", () => {
      rm.shapeless = input.value.split(",").map(x => x.trim()).filter(Boolean);
      onChange();
    });
    body.appendChild(input);
  } else if (rm.mode === "shaped") {
    const hint = document.createElement("p");
    hint.className = "hint";
    hint.textContent = "Up to 3 rows of up to 3 symbols (space = empty). Map each symbol to a material below.";
    body.appendChild(hint);
    for (let i = 0; i < 3; i++) {
      const row = document.createElement("input");
      row.type = "text"; row.spellcheck = false; row.maxLength = 3;
      row.style.fontFamily = "monospace";
      row.placeholder = "row " + (i + 1);
      row.value = rm.pattern[i] || "";
      row.addEventListener("input", () => { rm.pattern[i] = row.value; syncKeysFromPattern(rm); drawKeys(); onChange(); });
      body.appendChild(row);
    }
    const keysWrap = document.createElement("div");
    keysWrap.style.marginTop = "6px";
    body.appendChild(keysWrap);
    const drawKeys = () => {
      keysWrap.innerHTML = "";
      for (const sym of symbolsOf(rm.pattern)) {
        const r = document.createElement("div");
        r.className = "row"; r.style.marginBottom = "6px";
        r.innerHTML = `<span style="width:1.5em;font-family:monospace;text-align:center">${esc(sym)}</span>
          <input type="text" data-keys="items" spellcheck="false" placeholder="MATERIAL" value="${esc(rm.keys[sym] || "")}">`;
        r.querySelector("input").addEventListener("input", (e) => { rm.keys[sym] = e.target.value.trim(); onChange(); });
        keysWrap.appendChild(r);
      }
    };
    drawKeys();
  }
}

/** Distinct non-space symbols used across the pattern rows, in first-seen order. */
function symbolsOf(pattern) {
  const seen = [];
  for (const row of pattern) {
    for (const ch of String(row)) {
      if (ch !== " " && !seen.includes(ch)) seen.push(ch);
    }
  }
  return seen;
}

/** Drop key entries whose symbol no longer appears in the pattern. */
function syncKeysFromPattern(rm) {
  const used = new Set(symbolsOf(rm.pattern));
  for (const k of Object.keys(rm.keys)) if (!used.has(k)) delete rm.keys[k];
}

/** A generic "key + value" row with rename, edit, and delete. */
function kvRow(key, value, keyPlaceholder, valPlaceholder, numeric, onChange, onDelete) {
  const row = document.createElement("div");
  row.className = "row";
  row.style.marginBottom = "6px";
  row.innerHTML = `
    <input type="text" data-k value="${esc(key)}" placeholder="${keyPlaceholder}" spellcheck="false">
    <input type="${numeric ? "number" : "text"}" data-v value="${esc(value)}" placeholder="${valPlaceholder}" spellcheck="false">
    <button class="danger" data-del>✕</button>`;
  const kEl = row.querySelector("[data-k]"), vEl = row.querySelector("[data-v]");
  const fire = () => onChange(kEl.value.trim(), vEl.value);
  kEl.addEventListener("change", fire);
  vEl.addEventListener("input", fire);
  row.querySelector("[data-del]").onclick = onDelete;
  return row;
}

function esc(s) {
  return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

// ── texture chips ────────────────────────────────────────────────────────────

function matTex(name) {
  if (!name) return null;
  return MCAssets.item(name) || MCAssets.blockSprite(name) || MCAssets.block(name, "side");
}
function paintChips() {
  chip($("ch-chip"), matTex(($("ch-block").value || "").trim()));
  chip($("ruined-chip"), matTex(($("ruined-mat").value || "").trim()));
}
function chip(canvasEl, tex) {
  if (!canvasEl) return;
  const c = canvasEl.getContext("2d");
  c.imageSmoothingEnabled = false;
  c.clearRect(0, 0, 16, 16);
  if (tex) c.drawImage(tex, 0, 0, 16, 16);
  else { c.fillStyle = "#3a3f46"; c.fillRect(2, 2, 12, 12); }
}
MCAssets.onReady(() => paintChips());

// ── static event wiring ──────────────────────────────────────────────────────

function bindStatic() {
  const bindChk = (id, apply) => $(id).addEventListener("change", e => { apply(e.target.checked); changed(); });
  const bindNum = (id, apply) => $(id).addEventListener("input", e => { apply(num(e.target.value, 0)); changed(); });
  const bindTxt = (id, apply) => $(id).addEventListener("input", e => { apply(e.target.value); changed(); });

  bindChk("cfg-debug", v => state.debug = v);
  bindChk("cfg-glint", v => sect("visuals").glint = v);
  bindChk("cfg-particles", v => sect("visuals").particles = v);
  bindChk("mc-enabled", v => sect("mcmmo").enabled = v);
  bindNum("mc-xp", v => sect("mcmmo").default_herbalism_xp = Math.max(0, Math.round(v)));
  bindNum("mc-chance", v => sect("mcmmo").herbalism_double_drop_chance = clamp(v, 0, 1));

  bindTxt("ch-block", v => { sect("crop_highlight").block = v.trim(); paintChips(); });
  bindNum("ch-thickness", v => sect("crop_highlight").thickness = clamp(v, 0.005, 0.5));
  bindChk("ch-glow", v => sect("crop_highlight").glow = v);
  bindTxt("ch-color", v => sect("crop_highlight").glow_color = v.trim());

  bindNum("ins-decay", v => sect("insanity").decay_per_check = v);
  bindNum("ins-dose", v => sect("insanity").dose_factor = v);
  bindNum("ins-craving", v => sect("insanity").craving_gain = v);
  bindNum("ins-withdrawal", v => sect("insanity").withdrawal_gain = v);
  bindNum("ins-damage", v => sect("insanity").damage_gain = v);

  bindTxt("ruined-mat", v => { sect("quality", "ruined_item").material = v.trim(); paintChips(); });
  bindTxt("ruined-name", v => sect("quality", "ruined_item").name = v);
  bindTxt("ruined-lore", v => sect("quality", "ruined_item").lore = v);

  bindNum("vf-default", v => sect("vanilla_foods").default_lifetime_minutes = Math.max(0, v));
  bindNum("vc-default", v => sect("vanilla_crops").default_outside_rate = clamp(v, 0, 1));

  $("btn-add-vf").onclick = () => {
    const items = sect("vanilla_foods", "items");
    let i = 1, name = "NEW_FOOD";
    while (items[name] !== undefined) name = "NEW_FOOD_" + i++;
    items[name] = 60; buildVanillaFoods(); changed();
  };
  $("btn-add-station").onclick = () => {
    const stations = sect("stations");
    let i = 1, name = "new_station";
    while (stations[name] !== undefined) name = "new_station_" + i++;
    stations[name] = { display_name: "New Station", texture: "", processes: [] };
    buildStations(); changed();
  };
  $("btn-add-bg").onclick = () => addGroup(sect("biome_groups"), "biome-groups", "new_biome_group");
  $("btn-add-cg").onclick = () => addGroup(sect("consumable_groups"), "consumable-groups", "new_group");
  $("btn-add-vc").onclick = () => {
    const crops = sect("vanilla_crops", "crops");
    let i = 1, name = "NEW_CROP";
    while (crops[name] !== undefined) name = "NEW_CROP_" + i++;
    crops[name] = { biomes: [], outside_rate: 0.5 };
    buildVanillaCrops(); changed();
  };

  $("btn-clear").onclick = () => {
    if (!confirm("Reset the config to defaults?")) return;
    state = defaultConfig(); bindForms(); changed();
  };
  $("btn-upload").onclick = () => $("file-input").click();
  $("file-input").onchange = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const doc = YAMLLite.parse(reader.result);
        if (!doc || typeof doc !== "object") throw new Error("Couldn't parse that file.");
        state = doc; bindForms(); changed();
      } catch (err) { alert("Could not read that config:\n" + err.message); }
      $("file-input").value = "";
    };
    reader.readAsText(file);
  };

  $("btn-dl").onclick = () => {
    const blob = new Blob([$("yaml-out").textContent], { type: "text/yaml" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob); a.download = "config.yml"; a.click();
    URL.revokeObjectURL(a.href);
  };
}

function addGroup(obj, rootId, base) {
  let i = 1, name = base;
  while (obj[name] !== undefined) name = base + "_" + i++;
  obj[name] = [];
  buildGroups(rootId, obj); changed();
}

// Copy button is matched by selector (the shared `$` helper is id-only).
function bindCopy() {
  const btn = document.querySelector('[data-copy="yaml-out"]');
  if (!btn) return;
  btn.onclick = () => {
    navigator.clipboard.writeText($("yaml-out").textContent).then(() => {
      btn.classList.add("copied"); btn.textContent = "copied!";
      setTimeout(() => { btn.classList.remove("copied"); btn.textContent = "copy"; }, 1200);
    });
  };
}

// ── boot ─────────────────────────────────────────────────────────────────────

bindStatic();
bindCopy();
bindForms();
renderYAML();
